# Generated by Django 3.2 on 2021-11-15 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('sent_by', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('details', tinymce.models.HTMLField(blank=True)),
                ('level', models.CharField(blank=True, choices=[('info', 'Information'), ('', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('danger', 'Danger')], max_length=200)),
                ('sticky', models.BooleanField(default=False)),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
