# Generated by Django 3.2 on 2021-11-15 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import libs.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', models.ImageField(blank=True, upload_to='mugshots/', verbose_name='mugshot')),
                ('resume', models.FileField(blank=True, upload_to='resumes/', verbose_name='resume')),
                ('data', libs.fields.JSONField(blank=True, null=True)),
                ('preferences', libs.fields.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('url', models.URLField(blank=True, help_text="URL with a single '{user}' placeholder to turn a username into a service URL.", verbose_name='url')),
            ],
            options={
                'verbose_name': 'service type',
                'verbose_name_plural': 'service types',
                'db_table': 'user_service_types',
            },
        ),
        migrations.CreateModel(
            name='UserDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.degree')),
                ('graduation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username or id to be inserted into the service url.', max_length=100, verbose_name='Name or ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.servicetype')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'user_services',
            },
        ),
    ]
