# Generated by Django 3.2 on 2021-11-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntranetApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='images')),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Intranet Application',
            },
        ),
    ]
